[[params]]
#fastq_input = "fastq_pass/*.fastq.gz"
bam_input = "hifi_reads/*.bam"
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIB442-447.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3"
consensus_jobs = 30
consensus_jobs_per_align_job = 10
publish_consensus = true
publish_realign = true
output = "consensus"
