tsv = """\
barcode02	pLIB219,pLIB220
barcode03	pLIB219,pLIB220
barcode04	pLIB219,pLIB220
barcode05	pLIB219,pLIB222
barcode07	pLIB219,pLIB222
barcode08	pLIB219,pLIB222
barcode09	pLIB221,pLIB222
barcode10	pLIB221,pLIB222
barcode11	pLIB221,pLIB222
barcode12	pLIB219,pLIB220,pLIB221,pLIB222
"""

[[params]]
name = "default"

[[params]]
name = "10pct"
downsample_frac = 0.1

[[params]]
name = "bonito_10pct"
guppy_model = "res_dna_r941_min_crf_v032"
downsample_frac = 0.1
