tsv = """\
sample	references	min_read_length	max_read_length
NAO691_01	/Users/jacob/Downloads/NAO684.gb	-	-
NAO691_01	/Users/jacob/Downloads/NAO684.gb	9800	12000
NAO692_02	/Users/jacob/Downloads/NAO686.gb	-	-
NAO692_02	/Users/jacob/Downloads/NAO686.gb	2600	2800
NAO692_02	/Users/jacob/Downloads/NAO686.gb	4800	5200
NAO692_02	/Users/jacob/Downloads/NAO686.gb	9800	12000
NAO693_03	/Users/jacob/Downloads/NAO689.gb	-	-
NAO693_03	/Users/jacob/Downloads/NAO689.gb	2700	2900
NAO693_03	/Users/jacob/Downloads/NAO689.gb	4800	5100
NAO693_03	/Users/jacob/Downloads/NAO689.gb	9000	9200
NAO693_03	/Users/jacob/Downloads/NAO689.gb	9800	12000
"""

[[params]]
name = "${sample}${references ? '' : '_assembly'}_${min_read_length ?: 'na'}_to_${max_read_length ?: 'na'}"
fastq = "${sample}.fastq.gz"
