tsv = """\
sample	references	min_read_length	max_read_length
NAO692_02	/Users/jacob/Downloads/NAO686.gb	2600	2800
"""

[defaults]
name = "${sample}${references ? '' : '_assembly'}_${min_read_length ?: 'na'}_to_${max_read_length ?: 'na'}"
fastq = "${sample}.fastq.gz"

[[params]]
run_path = "ref"

[[params]]
ignore_references = true
run_path = "assembly"
