jobs: 1000
latency-wait: 60
rerun-incomplete: True
cluster: "sbatch -p {resources.partition} -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o ./logs_slurm/{rule}_{wildcards} -e ./logs_slurm/{rule}_{wildcards} {resources.optflags}"
