name: deaton-microscope
channels:
  - defaults
dependencies:
  - black
  - click
  - h5py
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - numpy
  - pandas
  - pyserial
  - pytables
