name: trenchripper
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - bokeh
  - cudatoolkit=10.2
  - dask
  - dask-jobqueue
  - dask-ml
  - datashader
  - distributed
  - fastparquet
  - h5py
  - holoviews
  - imgaug
  - ipympl
  - ipywidgets
  - jupyterlab
  - kmodes
  - line_profiler
  - lmfit
  - matplotlib-base
  - nd2reader
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - pulp
      - parse
      - h5py-cache
  - pyarrow
  - pytables
  - python=3.8.5
  - pytorch
  - qgrid
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tifffile
  - torchvision
  - tslearn
  - zarr
