name: marlin_libraries
channels:
  - pyviz
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - black
  - bokeh
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - minimap2
  - nodejs
  - numpy
  - pandas
  - pip
  - pre-commit
  - python=3.8
