name: marlin_libraries
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - dna_features_viewer
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - minimap2
  - nodejs
  - numpy
  - openssl=1.0
  - pandas
  - pathlib
  - pip
  - pre-commit
  - pydna
  - samtools
  - scikit-learn
  - seaborn
