[[params]]
#bam_input = "bam_pass/*.bam"
fastq_input = "fastq_pass/*.fastq.gz"
basecall = false
#pod5_input = "pod5/*.pod5"
pod5_chunk = true
pod5_split = true
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v5.0.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.3"
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIB473-476jqs.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3"
consensus_jobs = 400
consensus_jobs_per_align_job = 10
output = "prepare_reads"

[[params]]
run_path = "all_segments"
fastq_input = "fastq_pass/*.fastq.gz"
basecall = false
pod5_chunk = true
pod5_split = true
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v5.0.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.3"
gfa_grouping = "references/pLIB473-476jqs.gfa"
gfa_variants = "references/pLIB473-476jqs.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3"
consensus_jobs = 400
consensus_jobs_per_align_job = 10
output = "prepare_reads"
