[[params]]
name = "default"

[[params]]
name = "10pct"
downsample_frac = 0.1

[[params]]
name = "bonito_10pct"
guppy_model = "res_dna_r941_min_crf_v032"
downsample_frac = 0.1

[[samples]]
reads_prefix = "reads"
guppy_recall = true

[[samples]]
reads_prefix = "barcode02"
references = ["pLIB121", "pLIB122", "pLIB123"]

[[samples]]
reads_prefix = "barcode03"
references = ["pLIB121", "pLIB122", "pLIB123"]

[[samples]]
reads_prefix = "barcode04"
references = "pLT160,pLT161,pLT162,pLT163,pLT164,pLT165,pLT166,pLT167"
