name: trenchcoat
channels:
  - conda-forge
dependencies:
  - click
  - dask
  - ipywidgets
  - magicgui
  - matplotlib
  # For imwarp registration
  - napari
  - numba
  - numpy
  - pathlib
  - pyside2
  - pytables
  - ruamel.yaml
  - scikit-image
  - scipy
  - tqdm
  - xmltodict
