name: image_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - black
  - bokeh
  - cachetools
  - click
  - dask
  - dask-jobqueue
  - datashader
  - filelock
  - h5py
  - holoviews
  - hvplot
  - ipython
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - nd2reader
  - numba
  - numcodecs
  - numpy
  - numpy-indexed
  - pandas
  - panel
  - polars-u64-idx
  - py-opencv
  - pyarrow
  - pyinstrument
  - pymc
  - scikit-image
  - scikit-learn
  - scipy
  - split-file-reader
  - streamz
  - tornado
  - wrapt
  - xmltodict
  - zarr
