name: image_analysis
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cachetools
  - click
  - dask
  - dask-jobqueue
  - datashader
  - filelock
  - holoviews
  - hvplot
  - ipython
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numba
  - numcodecs
  - numpy
  - numpy-indexed
  - pandas
  - panel=0.12.7
  - peakutils
  - pyarrow
  - pytables
  - python-lmdb
  - qgrid
  - scikit-image
  - scikit-learn
  - scipy
  - streamz
  - tornado
  - wrapt
  - xmltodict
  - zarr
