tsv = """\
max_divergence
0.3
"""

[defaults]
fastq_input = "fastq_chunked/*.fastq.gz"
# prepare_reads_input = "prepare_reads/*.arrow"
basecall = false
#pod5_input = "pod5_split/*.pod5"
pod5_chunk = false
pod5_split = false
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v5.0.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.3"
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIB476jqs.gfa"
consensus_args = "--method abpoa --no-phred-output --max-length 10000 --max-divergence ${max_divergence}"
consensus_jobs = 400
consensus_jobs_per_align_job = 20
#output = "prepare_reads"
find_duplex_pairs_args = "-x UNS9,BC:T7_prom,BC:UMI:upstream,BC:UMI,BC:UMI:downstream,BC:spacer2,BC:Term_T7,BC:Term_T7hyb10"
prepare_reads_args = "-x UNS9,BC:T7_prom,BC:UMI:upstream,BC:UMI,BC:UMI:downstream,BC:spacer2,BC:Term_T7,BC:Term_T7hyb10"
run_path = "max_divergence=${max_divergence}"
