name: shenker-cloning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cachetools
  - click
  - clustalo
  - cytoolz
  - frozendict
  - gfapy
  - google-api-python-client
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jsondiff
  - jupyterlab
  - jupyterlab_code_formatter
  - mafft
  - matplotlib-base
  - natsort
  - nbformat
  - networkx
  - nextflow
  - nf-core
  - numpy
  - pandas
  - parasail-python
  - pip
  - pip:
      - benchlingapi
      - escapejson
      - primer3plus
      - pygsheets
      - pystream-protobuf
      - sqlalchemy-cockroachdb
  - primer3-py
  - protobuf
  - psycopg2
  - pyppeteer
  - pytoml
  - requests
  - requests-html
  - seaborn
  - sqlalchemy
  - tatsu
  - toml
  - tqdm
  - viennarna
  - xlrd
