name: shenker-cloning
channels:
  - pyviz
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cachetools
  - click
  - clustalo
  - cockroachdb-python
  - cytoolz
  - frozendict
  - google-api-python-client
  - holoviews
  - hvplot
  - ipywidgets
  - jsondiff
  - jupyterlab
  - jupyterlab_code_formatter
  - mafft
  - matplotlib
  - nbformat
  - nextflow
  - nf-core
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - benchlingapi
      - dnachisel
      - escapejson
      - primer3-py
      - primer3plus
      - requests-html
      - pygsheets
      - pyppeteer
  - psycopg2
  - pytoml
  - requests
  - seaborn
  - sqlalchemy
  - tatsu
  - tqdm
  - viennarna
  - xlrd
