[[params]]
#fastq_input = "fastq_pass/*.fastq.gz"
#bam_input = "bam_pass/*.bam"
basecall = false
pod5_input = "pod5_pass/*.pod5"
#pod5_input = "pod5_pass_split/*.pod5"
#pod5_chunk = false
pod5_chunk_bytes = 10737418240 # 10 GB
#pod5_split = false
#basecall = true
duplex = true
use_dorado_duplex_pairing = false
dorado_job_bytes = 10737418240 # 10 GB
# dorado_jobs = 10
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v4.3.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.2"
publish_pod5 = true
publish_bam = true
publish_fastq = true
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIB430-435.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3"
consensus_jobs = 400
consensus_jobs_per_align_job = 2
consensus_tabular_input = "consensus/*.arrow"
consensus_fasta_input = "consensus/*.fasta"
publish_consensus = true
publish_realign = true
#output = "consensus"
