name: crispri
channels:
  - pyviz
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cairo
  - cellrank
  - cudatoolkit=10.2
  - dask
  - dask-jobqueue
  - dask-ml
  - datashader
  - distributed
  - dna_features_viewer
  - fastparquet
  - goatools
  - h5py
  - holoviews
  - imgaug
  - ipympl
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - leidenalg
  - line_profiler
  - matplotlib
  - minimap2
  - nd2reader
  - networkx
  - nodejs
  - numpy
  - openpyxl
  - pandas
  - pip
  - pip:
      - pulp
      - parse
      - h5py-cache
  - pre-commit
  - pyarrow
  - pycairo
  - pytables
  - python=3.8.5
  - pytorch
  - qgrid
  - scanpy
  - scikit-image
  - scikit-learn
  - scipy
  - scvelo
  - seaborn
  - statsmodels
  - tifffile
  - torchvision
  - tslearn
  - umap-learn
  - zarr
