[[params]]
#bam_input = "bam_pass/*.bam"
consensus_tabular_input = "consensus/*.arrow"
consensus_fasta_input = "consensus/*.fasta"
basecall = false
#pod5_input = "pod5_pass_split/*.pod5"
pod5_chunk = false
pod5_split = false
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v4.3.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.2"
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIB429.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3"
consensus_jobs = 400
consensus_jobs_per_align_job = 10
output = "extract_segments"
