name: cloning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cachetools
  - click
  - clustalo
  - cytoolz
  - frozendict
  - google-api-python-client
  - jsondiff
  - jupyterlab
  - jupyterlab_code_formatter
  - libxml2=2.9.10
  - mafft
  - natsort
  - nbformat
  - nextflow
  - nf-core
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - benchlingapi
      - escapejson
      - primer3plus
      - pygsheets
      - sqlalchemy-cockroachdb
  - primer3-py
  - psycopg2
  - pyppeteer
  - pytoml
  - requests
  - requests-html
  - sqlalchemy
  - tatsu
  - tqdm
  - viennarna
