name: cloning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cachetools
  - click
  - clustalo
  - cytoolz
  - google-api-python-client
  - jupyterlab
  - mafft
  - nbformat
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - benchlingapi
      - escapejson
      - primer3-py
      - primer3plus
      - requests-html
      - pygsheets
      - docformatter
  - pre-commit
  - pytoml
  - requests
  - tqdm
