name: cloning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - bokeh
  - cachetools
  - click
  - clustalo
  - cytoolz
  - google-api-python-client
  - ipywidgets
  - jsondiff
  - jupyterlab=2.2.9
  - jupyterlab_code_formatter=1.3.8
  - mafft
  - nbformat
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - benchlingapi
      - escapejson
      - primer3-py
      - primer3plus
      - requests-html
      - pygsheets
      - pyppeteer
  - pre-commit
  - pysftp
  - pytoml
  - requests
  - snakemake-minimal
  - tatsu
  - tqdm
