name: deaton-microscope
channels:
  - defaults
dependencies:
  - black
  - cachetools
  - click
  - conda
  - h5py
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - pip
  - pip:
      - docformatter
  - pre-commit
  - pyserial
  - pytables
  - python=2.7
