name: nolsman-microscope
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cachetools
  - click
  - conda
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - nbformat
  - numpy
  - opencv
  - pandas
  - pip
  - pip:
      - docformatter
  - pre-commit
  - pyqt
  - python=2.7
