name: shenker-sequencing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awkward
  - biopython
  - black
  - click
  - mamba
  - cytoolz
  - dask
  - dask-jobqueue
  - distributed
  - gfapy
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - networkx
  - nextflow
  - numba
  - numpy
  - pandas
  - dnaio
  - parasail-python
  - pyabpoa
  - pysam
  - pyspoa
  - pywfa
  - polars-u64-idx=0.20.31
  - pyarrow
  - python
  - scipy
  - tqdm
