name: shenker-sequencing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awkward
  - biopython
  - black
  - conda
  - click
  - cytoolz
  - dask
  - dask-jobqueue
  - distributed
  - gfapy
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - mamba
  - matplotlib
  - networkx
  - nextflow=24.04.4 # TODO: see https://github.com/nextflow-io/nextflow/issues/5441
  - numba
  - numpy
  - pandas
  - dnaio
  - parasail-python
  - pip
  - pip:
    - pywfa
  - pyabpoa=1.5.2=py312he57d009_0 # TODO: waiting on https://github.com/yangao07/abPOA/issues/75
  - pysam
  - pyspoa
  - polars-u64-idx
  - pyarrow
  - python
  - scipy
  - tqdm
