name: shenker-sequencing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - conda
  - cytoolz
  - gfapy
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - networkx
  - nextflow
  - pandas
  - pip
  - pip:
      - pyfastx
  - pyarrow
  - python
  - tqdm
