name: shenker-sequencing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - black
  - gfapy
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - nextflow
  - pandas
  - pyarrow
  - python
  - tqdm
