name: shenker-sequencing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awkward
  - biopython
  - black
  - click
  - conda
  - cytoolz
  - gfapy
  - holoviews
  - hvplot
  - ipywidgets
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - networkx
  - nextflow
  - numba
  - numpy
  - pandas
  - pip
  - pip:
      # NOTE: must module load gcc/9.2.0 to build pywfa
      - dnaio # via pip until bioconda starts building for python 3.11/3.12
      - parasail # via pip until bioconda starts building for python 3.11/3.12
      - polars-u64-idx
      - pysam # via pip until bioconda starts building for python 3.11/3.12
      - pywfa # via pip until bioconda starts building for python 3.11/3.12
  - pyarrow
  - python
  - tqdm
  - xopen # for dnaio
