name: circuit_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - holoviews
  - hvplot
  - ipywidgets
  - julia
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - pandas
  - pip
