name: sigma_circuits
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - cachetools
  - cytoolz
  - dask
  - dask-image
  - dask-jobqueue
  - datashader
  - distributed
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - nd2reader
  - numpy
  - pandas
  - panel
  - python>=3.8.8
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - zarr
