name: image_analysis
channels:
  - conda-forge
dependencies:
  - bokeh
  - cachetools
  - click
  - dask
  - dask-jobqueue
  - datashader
  - filelock
  - holoviews
  - hvplot
  - ipython
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numba
  - numcodecs
  - numpy
  - numpy-indexed
  - pandas
  - panel
  - peakutils
  - pip
  - pyarrow
  - qgrid
  - scikit-image
  - scikit-learn
  - scipy
  - streamz
  - tornado
  - wrapt
  - xmltodict
  - zarr
  - pip:
    - git+https://git@github.com/paulssonlab/nd2reader.git
