[[params]]
bam_input = "bam_pass/*.bam"
basecall = false
#pod5_input = "pod5_pass_split/*.pod5"
pod5_chunk = false
pod5_split = false
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v5.0.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.3"
gfa_grouping = "references/barcode.gfa"
gfa_variants = "references/pLIBxxx.gfa"
consensus_args = "--method abpoa --no-phred-output --min-depth 3 --limit-depth 100"
consensus_jobs = 400
consensus_jobs_per_align_job = 10
output = "consensus"
