name: paulssonlab
channels:
  - defaults
dependencies:
  - pre-commit
  - nbstripout
  - cytoolz
  - freetype
  - jupyterlab
  - matplotlib
  - scipy
  - numpy
  - pint
  - freetype-py
  - click
  - shortuuid
