name: snakenbake
channels:
  - conda-forge
  - defaults
dependencies:
  - bitarray
  - black
  - cachetools
  - click
  - click
  - cytoolz
  - freetype
  - freetype-py
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - nbformat
  - numpy
  - pint
  - pip
  - pip:
      - gdspy
      - docformatter
  - pip
  - pre-commit
  - scipy
  - shortuuid
