name: snakenbake
channels:
  - conda-forge
  - defaults
dependencies:
  - shortuuid
  - freetype
  - freetype-py
  - cytoolz
  - matplotlib
  - pint
  - numpy
  - click
  - jupyterlab
  - scipy
  - bitarray
  - pip
  - pip:
    - gdspy
