name: snakenbake
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - scipy
  - freetype
  - numpy
  - pint
  - shortuuid
  - cytoolz
  - click
  - pre-commit
  - freetype-py
  - jupyterlab
  - pip
  - pip:
    - gdspy
