name: snakenbake
channels:
  - conda-forge
  - defaults
dependencies:
  - bitarray
  - click
  - cytoolz
  - freetype
  - freetype-py
  - jupyterlab
  - matplotlib
  - numpy
  - pint
  - pip
  - pip:
      - gdspy
  - scipy
  - shortuuid
