name: snakenbake
channels:
  - conda-forge
  - defaults
dependencies:
  - bitarray
  - black
  - cachetools
  - cytoolz
  - gdstk
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - pint
  - scipy
  - shortuuid
