name: nolsman-microscope
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - click
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pre-commit
  - pyqt
