Phase_TRIPLE:
    rgb            : False
    multiscale     : False
    colormap       : "gray"
    contrast_limits:
        - 100
        - 65535
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "Brightfield"
    opacity        : 1.0
    blending       : "additive"
    visible        : True

YFP:
    rgb            : False
    multiscale     : False
    colormap       : "yellow"
    contrast_limits:
        - 100
        - 10000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "mVenus"
    opacity        : 1.0
    blending       : "additive"
    visible        : True

MCHERRY:
    rgb            : False
    multiscale     : False
    colormap       : "red"
    contrast_limits:
        - 100
        - 10000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "mKate2"
    opacity        : 1.0
    blending       : "additive"
    visible        : True 
