Phase:
    rgb            : False
    multiscale     : False
    colormap       : "gray_trans"
    contrast_limits:
        - 100
        - 1000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "Phase contrast"
    opacity        : 1.0
    blending       : "additive"
    visible        : True

CFP:
    rgb            : False
    multiscale     : False
    colormap       : "cyan"
    #contrast_limits:
        #- 100
        #- 1000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "mSCFP3"
    opacity        : 1.0
    blending       : "additive"
    visible        : True

YFP:
    rgb            : False
    multiscale     : False
    colormap       : "yellow"
    #contrast_limits:
        #- 100
        #- 1000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "mVenus"
    opacity        : 1.0
    blending       : "additive"
    visible        : True

MCHERRY:
    rgb            : False
    multiscale     : False
    colormap       : "red"
    #contrast_limits:
        #- 100
        #- 1000
    gamma          : 1.0
    interpolation  : "nearest"
    name           : "mKate2"
    opacity        : 1.0
    blending       : "additive"
    visible        : True
