repos:
-   repo: local
    hooks:
    - id: black
      name: Format .py files
      entry: black
      language: system
      types: [python]
    - id: jupytext
      name: Format .ipynb files
      entry: jupytext --quiet --from ipynb --pipe black
      language: system
      files: \.ipynb$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
