name: fp_aggregation
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cachetools
  - click
  - cytoolz
  - dask
  - dask-jobqueue
  - datashader
  - distributed
  - holoviews
  - hvplot
  - jupyterlab
  - matplotlib
  - nbformat
  - nd2reader
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - docformatter
  - pre-commit
  - scikit-image
  - scipy
