name: fp_aggregation
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cytoolz
  - dask
  - dask-jobqueue
  - datashader
  - distributed
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - nd2reader
  - numpy
  - pandas
  - scikit-image
  - scipy
