name: lab_helper
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - click
  - cytoolz
  - google-api-python-client
  - holoviews
  - jupyterlab
  - jupyterlab_code_formatter
  - numpy
  - pandas
  - pytoml
  - requests
