name: lab_helper
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - black
  - cachetools
  - click
  - cytoolz
  - google-api-python-client
  - holoviews
  - jupyterlab
  - nbformat
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - docformatter
  - pre-commit
  - pytoml
  - requests
