[[params]]
fastq_input = "fastq_pass/*.fastq.gz"
pod5_input = "pod5_pass/*.pod5"
pod5_chunk_bytes = 1073741824 # 1 GB
#pod5_chunk_files = 3
basecall = true
duplex = true
dorado_model = "dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
dorado_duplex_model = "dna_r10.4.1_e8.2_5khz_stereo@v1.1"
