name: nanopore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - dask
  - dask-jobqueue
  - distributed
  - graphaligner
  - jupyterlab
  - matplotlib
  - medaka
  - minimap2
  - nodejs
  - numpy
  - pandas
  - pip
  - pre-commit
  - samtools
  - seaborn
  - snakemake
  - vg
