name: nanopore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - black
  - graphaligner
  - jupyterlab
  - matplotlib
  - medaka
  - minimap2
  - nodejs
  - numpy
  - pandas
  - pip
  - pre-commit
  - samtools
  - seaborn
  - snakemake
  - vg
