name: matriarch
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cachetools
  - click
  - dask
  - dask-jobqueue
  - datashader
  - filelock
  - holoviews
  - ipython
  - ipywidgets
  - matplotlib
  - nd2reader
  - numba
  - numcodecs
  - numpy
  - numpy-indexed
  - pandas
  - peakutils
  - pyarrow
  - qgrid
  - scikit-image
  - scikit-learn
  - scipy
  - tornado
  - zarr
