name: molecule_counting
channels:
  - http://conda.anaconda.org/gurobi
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cachetools
  - click
  - cytoolz
  - dask
  - dask-jobqueue
  - datashader
  - distributed
  - holoviews
  - hvplot
  - jupyterlab
  - matplotlib
  - nbformat
  - nd2reader
  - nodejs
  - numpy
  - numpy-indexed
  - numpy_groupies
  - pandas
  - panel
  - peakutils
  - pre-commit
  - pyarrow
  - scikit-image
  - scipy
  - seaborn
  - zarr
