name: molecule_counting
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - bokeh
  - cachetools
  - click
  - cytoolz
  - dask
  - dask-jobqueue
  - datashader
  - distributed
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - nbformat
  - nd2reader
  - nodejs
  - numpy
  - pandas
  - panel
  - pre-commit
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - zarr
